import type { MultiPolygon } from './scoring';

/**
 * Boundary shapes, keyed by Census GEOID, generated by scripts/build-locations.mjs.
 * Loaded once in the background; every consumer goes through getShape() so a
 * future backend can replace this static file without touching callers.
 */
let shapes: Record<string, MultiPolygon> | null = null;
let loadPromise: Promise<void> | null = null;

/** Kick off (or join) the one background load. Never rejects. */
export function startShapeLoad(url = '/shapes-pr.json'): Promise<void> {
  loadPromise ??= fetch(url)
    .then(async (response) => {
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      shapes = (await response.json()) as Record<string, MultiPolygon>;
    })
    .catch((error: unknown) => {
      // Not fatal: reveals fall back to pin-only, scoring to point distance.
      console.warn('Shape data unavailable — playing without boundaries.', error);
    });
  return loadPromise;
}

/** Shape for a geoid, or undefined if unknown / not yet loaded / load failed. */
export function getShape(geoid: string | undefined): MultiPolygon | undefined {
  if (!geoid || !shapes) return undefined;
  const value = shapes[geoid];
  // Guard against malformed data (e.g. a future backend swap) feeding a
  // truthy non-MultiPolygon value into the geometry code downstream.
  const isMultiPolygon =
    Array.isArray(value) &&
    value.length > 0 &&
    Array.isArray(value[0]) &&
    Array.isArray(value[0][0]) &&
    Array.isArray(value[0][0][0]);
  return isMultiPolygon ? value : undefined;
}

export function resetShapesForTest(): void {
  shapes = null;
  loadPromise = null;
}
