import { z } from 'zod';

/**
 * The set of coordinates a legitimate client can actually produce.
 *
 * Mirrors PR_BOUNDS in src/components/MapView.tsx (`L.latLngBounds([17.8,
 * -68.0], [18.6, -65.1])` with maxBoundsViscosity 1.0), so the map physically
 * cannot pan or be clicked outside this box. Bounding to the island rather than
 * to the globe is the whole point: a swapped lat/lng scores a clean 0 today and
 * reads as a terrible guess instead of a bug, and lat: 999 does the same.
 *
 * Deliberately tighter than the location table's CHECK constraints (17.5..18.8 /
 * -68.2..-64.9, which have to admit Mona and Desecheo and territorial water in
 * the county polygons). The database bound protects the data; this one protects
 * the request.
 */
export const PR_BOUNDS = {
  minLat: 17.8,
  maxLat: 18.6,
  minLng: -68.0,
  maxLng: -65.1,
} as const;

/**
 * Hand-rolled rather than z.string().uuid() / z.uuid(): the former is deprecated
 * in zod 4 and the latter does not exist in zod 3, and a regex is immune to
 * both. puzzle_round.id is generated by gen_random_uuid(), so it is always
 * version 4, but the pattern stays permissive about the version nibble.
 */
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

const coordinate = (min: number, max: number) =>
  z
    .number()
    // z.number() already rejects NaN, but not every zod version rejects
    // Infinity, and JSON.parse('{"lat":1e999}') really does yield Infinity.
    .refine((value) => Number.isFinite(value), { message: 'must be a finite number' })
    .min(min)
    .max(max);

/**
 * The guess request body.
 *
 * Everything downstream — haversineKm, nearestPointOnShape, scoreForDistance —
 * is unguarded arithmetic that propagates a bad number silently: Math.max(0,
 * NaN) is NaN, and JSON.stringify(NaN) is null, so an unvalidated body ships
 * {"points": null} with a 200. Worse, the failure is not even consistent: the
 * same NaN scores {"points": null} against a circle target but {"points": 0,
 * "distanceKm": null} against a shape, because nearestPointOnShape seeds its
 * best distance at Infinity and every NaN comparison loses. This schema is the
 * only thing standing between the request and that arithmetic.
 */
export const guessBodySchema = z.object({
  roundId: z.string().regex(UUID_RE, 'roundId must be a uuid'),
  lat: coordinate(PR_BOUNDS.minLat, PR_BOUNDS.maxLat),
  lng: coordinate(PR_BOUNDS.minLng, PR_BOUNDS.maxLng),
});

export type GuessBody = z.infer<typeof guessBodySchema>;
