#!/usr/bin/env node
// Seeds the `shape` and `location` tables from the checked-in source data.
//
// Run with:  node --env-file=.env scripts/seed.mjs
//
// Source of truth stays in the repo, not the database: src/data/curated.ts is
// hand-maintained, src/data/tiger.generated.ts is regenerated by
// scripts/build-locations.mjs, and public/shapes-pr.json is generated with it.
// The database is a projection of those files, which is why this script must
// stay re-runnable -- every regen ends with running it again.
//
// Zero dependencies beyond the Neon driver, matching the house style of
// scripts/build-locations.mjs.

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { neon } from '@neondatabase/serverless';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

// The repo's own "greater Puerto Rico" envelope, lifted from
// src/data/shapes-dataset.test.ts and duplicated in the CHECK constraints of
// migrations/001_initial.sql. Generous on purpose: includes territorial water
// in the county polygons plus Mona, Desecheo and the Culebra cays.
const BOUNDS = { minLat: 17.5, maxLat: 18.8, minLng: -68.2, maxLng: -64.9 };

const CATEGORIES = new Set(['municipio', 'landmark', 'barrio']);
const SUBTYPES = new Set(['municipio', 'landmark', 'barrio', 'barrio-pueblo', 'comunidad']);
const DIFFICULTIES = new Set(['easy', 'medium', 'hard']);
const SOURCES = new Set(['geonames', 'curated', 'tiger-cousub', 'tiger-place']);

/**
 * Pull an exported array literal out of a .ts file as raw text.
 *
 * Node cannot import TypeScript, and this repo has no tsx/ts-node and is not
 * adding one (four runtime dependencies is a deliberate constraint). The two
 * data modules are machine-formatted arrays of plain object literals with no
 * expressions, function calls or references, so slicing the literal out and
 * evaluating it yields exactly the same values TypeScript produces --
 * scripts/seed.test.mjs asserts precisely that against the real module.
 *
 * @param {string} source  full text of the .ts file
 * @param {string} exportName  e.g. 'CURATED_LOCATIONS'
 * @returns {string}  the literal, from '[' through the matching ']'
 */
export function extractArrayLiteral(source, exportName) {
  const marker = `export const ${exportName}: GameLocation[] = [`;

  const start = source.indexOf(marker);
  if (start === -1) {
    throw new Error(`extractArrayLiteral: no "export const ${exportName}: GameLocation[] = [" found`);
  }
  if (source.indexOf(marker, start + 1) !== -1) {
    throw new Error(
      `extractArrayLiteral: "${exportName}" is declared more than once. This ` +
        'function relies on the array being the only one in the file (it ends ' +
        'the literal at the last "];"), so a second declaration is unsafe.',
    );
  }

  // -1 puts us on the '[' that the marker ends with.
  const open = start + marker.length - 1;
  const close = source.lastIndexOf('];');
  if (close < open) {
    throw new Error(`extractArrayLiteral: no closing "];" after ${exportName}`);
  }

  return source.slice(open, close + 1);
}

function evaluateArrayLiteral(literal, label) {
  // new Function rather than eval: the literal is evaluated in its own scope
  // with nothing from here in view, so a stray identifier in the data throws
  // instead of silently resolving to a local.
  try {
    return new Function(`return ${literal};`)();
  } catch (error) {
    throw new Error(`Failed to evaluate the ${label} array literal: ${error.message}`);
  }
}

/**
 * Read all 1088 locations and all 1422 shapes off disk.
 *
 * @returns {{ locations: object[], shapes: Record<string, unknown> }}
 */
export function loadSeedData() {
  const curatedSource = readFileSync(join(ROOT, 'src', 'data', 'curated.ts'), 'utf8');
  const tigerSource = readFileSync(join(ROOT, 'src', 'data', 'tiger.generated.ts'), 'utf8');

  // Curated first, matching src/data/locations.ts, so any first-match-wins
  // lookup downstream prefers the hand-vetted rows.
  const locations = [
    ...evaluateArrayLiteral(extractArrayLiteral(curatedSource, 'CURATED_LOCATIONS'), 'curated'),
    ...evaluateArrayLiteral(extractArrayLiteral(tigerSource, 'TIGER_LOCATIONS'), 'tiger'),
  ];

  const shapes = JSON.parse(readFileSync(join(ROOT, 'public', 'shapes-pr.json'), 'utf8'));

  return { locations, shapes };
}

/**
 * Fail fast, with a readable message, on anything the database would reject
 * halfway through a 1088-row insert. Every check here mirrors a constraint in
 * migrations/001_initial.sql; the point is to name the offending row instead
 * of surfacing "violates check constraint location_target_xor" with no id.
 *
 * @param {{ locations: object[], shapes: Record<string, unknown> }} data
 */
export function assertSeedInvariants({ locations, shapes }) {
  const seenIds = new Set();
  const seenGeoids = new Set();

  for (const location of locations) {
    const label = `location ${location.id} (${location.name})`;

    if (seenIds.has(location.id)) {
      throw new Error(`Duplicate location id ${location.id} (${location.name})`);
    }
    seenIds.add(location.id);

    if (!CATEGORIES.has(location.category)) throw new Error(`${label}: bad category ${location.category}`);
    if (!SUBTYPES.has(location.subtype)) throw new Error(`${label}: bad subtype ${location.subtype}`);
    if (!DIFFICULTIES.has(location.difficulty)) throw new Error(`${label}: bad difficulty ${location.difficulty}`);
    if (!SOURCES.has(location.source)) throw new Error(`${label}: bad source ${location.source}`);

    // The XOR. This is the api/guess.ts SHAPE-vs-CIRCLE discriminant: a row
    // with neither has nothing to score against, a row with both is ambiguous.
    const hasGeoid = location.geoid != null;
    const hasRadius = location.radiusKm != null;
    if (hasGeoid === hasRadius) {
      throw new Error(
        `${label}: must carry exactly one of geoid / radiusKm ` +
          `(geoid=${location.geoid}, radiusKm=${location.radiusKm})`,
      );
    }

    if (hasGeoid) {
      if (seenGeoids.has(location.geoid)) {
        throw new Error(`${label}: geoid ${location.geoid} is already used by another location`);
      }
      seenGeoids.add(location.geoid);

      if (!Object.prototype.hasOwnProperty.call(shapes, location.geoid)) {
        throw new Error(`${label}: geoid ${location.geoid} has no entry in public/shapes-pr.json`);
      }
    }

    if (hasRadius && !(location.radiusKm > 0)) {
      throw new Error(`${label}: radiusKm must be > 0, got ${location.radiusKm}`);
    }

    if (
      !Number.isFinite(location.lat) ||
      !Number.isFinite(location.lng) ||
      location.lat < BOUNDS.minLat ||
      location.lat > BOUNDS.maxLat ||
      location.lng < BOUNDS.minLng ||
      location.lng > BOUNDS.maxLng
    ) {
      throw new Error(
        `${label}: coordinates out of bounds (${location.lat}, ${location.lng}). ` +
          'A swapped lat/lng pair looks exactly like this.',
      );
    }
  }
}

function chunk(items, size) {
  const out = [];
  for (let i = 0; i < items.length; i += size) out.push(items.slice(i, i + size));
  return out;
}

async function seedShapes(sql, shapes) {
  const entries = Object.entries(shapes);

  // 25 rows per statement. Shapes average ~1.1 KB of JSON and top out at
  // 8.6 KB (Utuado), so a chunk stays well under any HTTP request-size limit
  // while still cutting 1422 round trips down to 57.
  for (const batch of chunk(entries, 25)) {
    const values = [];
    const params = [];

    for (const [geoid, geometry] of batch) {
      const base = params.length;
      values.push(`($${base + 1}, $${base + 2}::jsonb)`);
      // JSON.stringify, not the raw array: the driver would otherwise
      // serialise a JS array into a Postgres ARRAY literal ('{...}'), which
      // is not jsonb and fails with a type error. The explicit ::jsonb cast
      // then turns the text parameter into the column's type.
      params.push(geoid, JSON.stringify(geometry));
    }

    await sql.query(
      `INSERT INTO shape (geoid, geometry) VALUES ${values.join(', ')}
       ON CONFLICT (geoid) DO UPDATE SET geometry = EXCLUDED.geometry`,
      params,
    );
  }

  return entries.length;
}

async function seedLocations(sql, locations) {
  // 100 rows x 11 parameters = 1100 bind parameters per statement, comfortably
  // under Postgres's 65535 limit and small enough that a failure names a
  // narrow batch.
  for (const batch of chunk(locations, 100)) {
    const values = [];
    const params = [];

    for (const location of batch) {
      const base = params.length;
      values.push(
        `($${base + 1}, $${base + 2}, $${base + 3}, $${base + 4}, $${base + 5}, ` +
          `$${base + 6}, $${base + 7}, $${base + 8}, $${base + 9}, $${base + 10}, $${base + 11})`,
      );
      params.push(
        location.id,
        location.name,
        location.municipio,
        location.category,
        location.subtype,
        location.difficulty,
        location.source,
        // `geoid` and `radiusKm` are ABSENT keys in the source data, not null.
        // Binding `undefined` would send the string "undefined" or error, so
        // normalise here.
        location.geoid ?? null,
        location.radiusKm ?? null,
        location.lat,
        location.lng,
      );
    }

    await sql.query(
      `INSERT INTO location
         (id, name, municipio, category, subtype, difficulty, source, geoid, radius_km, lat, lng)
       VALUES ${values.join(', ')}
       ON CONFLICT (id) DO UPDATE SET
         name       = EXCLUDED.name,
         municipio  = EXCLUDED.municipio,
         category   = EXCLUDED.category,
         subtype    = EXCLUDED.subtype,
         difficulty = EXCLUDED.difficulty,
         source     = EXCLUDED.source,
         geoid      = EXCLUDED.geoid,
         radius_km  = EXCLUDED.radius_km,
         lat        = EXCLUDED.lat,
         lng        = EXCLUDED.lng`,
      params,
    );
  }

  return locations.length;
}

async function main() {
  const databaseUrl = process.env.DATABASE_URL;
  if (!databaseUrl) {
    console.error('DATABASE_URL is not set. Copy .env.example to .env and fill it in, then run:');
    console.error('  node --env-file=.env scripts/seed.mjs');
    process.exit(1);
  }

  const data = loadSeedData();
  assertSeedInvariants(data);

  console.log(
    `Loaded ${data.locations.length} locations and ${Object.keys(data.shapes).length} shapes.`,
  );

  const sql = neon(databaseUrl);

  // Shapes FIRST. location.geoid is a foreign key to shape.geoid, so the
  // referenced rows have to exist before any location is inserted.
  //
  // All 1422 shapes go in, not just the 1063 that a location references. The
  // extra 359 are ~240 KB and exist for the ?debug=shapes boundary-QA overlay,
  // and having them present means a future curated row can point at an
  // existing Census unit without a re-seed.
  const shapeCount = await seedShapes(sql, data.shapes);
  console.log(`  shapes    ${shapeCount} upserted`);

  const locationCount = await seedLocations(sql, data.locations);
  console.log(`  locations ${locationCount} upserted`);

  // Note deliberately NOT done: deleting rows that disappeared from the source
  // files. puzzle_round.location_id references location(id), so a delete would
  // either fail or orphan scheduled puzzles. Removing a location is a manual,
  // considered operation -- not a side effect of re-seeding.
  console.log('Seed complete.');
}

// Importing this module must never open a connection: scripts/seed.test.mjs
// exercises the pure functions above with no database in sight.
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  await main();
}
